# ═══════════════════════════════════════════════════
# PROFIL DEV — Développement local
# ═══════════════════════════════════════════════════

# Hibernate peut créer/mettre à jour le schéma en dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logs détaillés
logging.level.com.klodit.soumission_service=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Swagger toujours activé
springdoc.swagger-ui.enabled=true
