apiVersion: v1
kind: ConfigMap
metadata:
  name: soumission-service-config
  namespace: al-mizan
  labels:
    app: soumission-service
data:
  # ── Spring ───────────────────────────────────
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8004"

  # ── Services externes ───────────────────────
  AO_SERVICE_URL: "http://appel-offre-service.al-mizan.svc.cluster.local:8003"
  USER_SERVICE_URL: "http://utilisateur-service.al-mizan.svc.cluster.local:8002"

  # ── RabbitMQ ────────────────────────────────
  SPRING_RABBITMQ_HOST: "rabbitmq.al-mizan.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"

  # ── Redis ───────────────────────────────────
  SPRING_DATA_REDIS_HOST: "redis.al-mizan.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"

  # ── MySQL ───────────────────────────────────
  MYSQL_HOST: "mysql.al-mizan.svc.cluster.local"
  MYSQL_PORT: "3306"

  # ── MinIO ───────────────────────────────────
  MINIO_URL: "http://minio.al-mizan.svc.cluster.local:9000"

  # ── Shamir ──────────────────────────────────
  SHAMIR_TOTAL_SHARES: "5"
  SHAMIR_THRESHOLD: "3"

  # ── Rate Limiting ──────────────────────────
  RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
